name: capture
on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/shark.yml
  pull_request: {}
jobs:
   build:
      name: wireshark
      runs-on: macos-latest
      steps:
         - name: setup shark
           run: |
            brew install wireshark
            brew install --cask wireshark-chmodbpf
         - name: try wireshark
           run: tshark -i en0 -c 5
