name: capture
on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/shark.yml
  pull_request: {}
jobs:
   build:
      name: wireshark
      runs-on: macos-latest
      steps:
         - name: setup shark
           run: brew install wireshark
         - name: try wireshark
           run: tshark --help
