name: capture
on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/shark.yml
  pull_request: {}
jobs:
   shark:
      name: wireshark
      runs-on: macos-latest
      steps:
         - name: setup shark
           run: |
            brew install wireshark
            brew install --cask wireshark-chmodbpf
         - name: Checkout repository
           uses: actions/checkout@v2
         - name: try wireshark
           run: tshark -i en0 -a duration:60 -w capture.pcap
         - name: pip
           run: pip install pandas

